version: 2
updates:
  - package-ecosystem: "bundler"
    directories:
      - "/stimulus-plumbers-rails"
      - "/stimulus-plumbers-tailwind"
      - "/stimulus-plumbers-mcp"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/stimulus-plumbers"
      - "/stimulus-plumbers-tailwind"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
