# frozen_string_literal: true

require "pathname"

module StimulusPlumbers
  module Tailwind
    module Generators
      module SourcesDirective
        GEM_NAME = "stimulus_plumbers_tailwind"
        LIB_DIR  = File.expand_path("../../..", __dir__)
        SOURCES_CSS_PATH = "app/assets/builds/stimulus_plumbers/tailwind.css"

        module_function

        def import_directive(from:, destination_root:)
          path = Pathname.new(destination_root).join(SOURCES_CSS_PATH)
          rel  = path.relative_path_from(Pathname.new(from))
          rel  = "./#{rel}" unless rel.to_s.start_with?(".", "/")
          %(@import "#{rel}";)
        end

        def source_line(from:)
          rel = Pathname.new(LIB_DIR).relative_path_from(Pathname.new(from))
          %(@source "#{rel}/**/*.rb";)
        end

        def file_contents(from:)
          <<~CSS
            /*
             * Auto-generated by stimulus_plumbers:tailwind:install.
             * Holds a single @source pointing to the stimulus_plumbers_tailwind gem so the Tailwind CLI can scan its component class lists.
             * The path is absolute to this machine, so this file is git-ignored and regenerated on assets:precompile / tailwindcss:build.
             * Do not edit by hand.
             */
            #{source_line(from: from)}
          CSS
        end

        def anchor_pattern
          %r{@import "tailwindcss"[^;]*;}
        end

        def stale_pattern
          Regexp.union(
            %r{@source "[^"]*#{Regexp.escape(GEM_NAME)}[^"]*";},
            %r{@import "[^"]*#{Regexp.escape(SOURCES_CSS_PATH)}";},
            %r{@import "[^"]*stimulus_plumbers/tailwind/sources\.css";}
          )
        end

        def removal_pattern(from:)
          Regexp.union(stale_pattern, Regexp.new(Regexp.escape(source_line(from: from))))
        end
      end
    end
  end
end
