# frozen_string_literal: true

require "test_helper"
require "stimulus_plumbers/tailwind/generators/sources_directive"

class TailwindGeneratorsSourcesDirectiveTest < Minitest::Test
  def test_import_directive_builds_import_line_relative_to_the_css_file_directory
    destination_root = "/app"
    css_dir          = "#{destination_root}/app/assets/stylesheets"

    assert_equal(
      %(@import "../builds/stimulus_plumbers/tailwind.css";),
      StimulusPlumbers::Tailwind::Generators::SourcesDirective.import_directive(
        from: css_dir, destination_root: destination_root
      )
    )
  end

  def test_source_line_builds_source_line_relative_to_the_partial_directory
    gem_lib_dir = "#{Gem.loaded_specs["stimulus_plumbers_tailwind"].gem_dir}/lib"
    partial_dir = "/app/assets/builds/stimulus_plumbers"
    expected    = Pathname.new(gem_lib_dir).relative_path_from(Pathname.new(partial_dir))

    assert_equal(
      %(@source "#{expected}/**/*.rb";),
      StimulusPlumbers::Tailwind::Generators::SourcesDirective.source_line(from: partial_dir)
    )
  end

  def test_file_contents_composes_the_comment_header_and_source_line
    partial_dir = "/app/assets/builds/stimulus_plumbers"

    assert_equal <<~CSS, StimulusPlumbers::Tailwind::Generators::SourcesDirective.file_contents(from: partial_dir)
      /*
       * Auto-generated by stimulus_plumbers:tailwind:install.
       * Holds a single @source pointing to the stimulus_plumbers_tailwind gem so the Tailwind CLI can scan its component class lists.
       * The path is absolute to this machine, so this file is git-ignored and regenerated on assets:precompile / tailwindcss:build.
       * Do not edit by hand.
       */
      #{StimulusPlumbers::Tailwind::Generators::SourcesDirective.source_line(from: partial_dir)}
    CSS
  end

  def test_anchor_pattern_matches_the_tailwindcss_import_line
    assert_match StimulusPlumbers::Tailwind::Generators::SourcesDirective.anchor_pattern, %(@import "tailwindcss";)
  end

  def test_stale_pattern_matches_a_prior_source_from_a_different_gem_path
    old_line = %(@source "/old/gems/stimulus_plumbers_tailwind-0.0.1/lib/**/*.rb";)

    assert_match StimulusPlumbers::Tailwind::Generators::SourcesDirective.stale_pattern, old_line
  end

  def test_stale_pattern_matches_the_prior_entry_relative_sources_import
    assert_match(
      StimulusPlumbers::Tailwind::Generators::SourcesDirective.stale_pattern,
      %(@import "./stimulus_plumbers/tailwind/sources.css";)
    )
  end

  def test_stale_pattern_matches_a_prior_relative_builds_import
    assert_match(
      StimulusPlumbers::Tailwind::Generators::SourcesDirective.stale_pattern,
      %(@import "./app/assets/builds/stimulus_plumbers/tailwind.css";)
    )
  end

  def test_stale_pattern_does_not_match_an_unrelated_source
    refute_match StimulusPlumbers::Tailwind::Generators::SourcesDirective.stale_pattern, %(@source "./app/views/**/*.erb";)
  end

  def test_removal_pattern_matches_stale_and_current_machine_source_directives
    directive   = StimulusPlumbers::Tailwind::Generators::SourcesDirective
    partial_dir = "/app/assets/stylesheets"

    assert_match directive.removal_pattern(from: partial_dir), %(@source "/old/stimulus_plumbers_tailwind/lib/**/*.rb";)
    assert_match directive.removal_pattern(from: partial_dir), directive.source_line(from: partial_dir)
  end
end
