# frozen_string_literal: true

require "minitest/test_task"

namespace "test:unit" do
  Minitest::TestTask.create(:coverage) do |t|
    t.test_globs = ["test/stimulus_plumbers/**/*_test.rb"]
    t.test_prelude = %(require "simplecov"; SimpleCov.start)
    t.warning = false
  end
end

namespace :coverage do
  desc "Run coverage with spec"
  task :run do
    Rake::Task["test:unit:coverage"].invoke
  end

  desc "Collate coverage results generated by different test runners"
  task :report do
    require "simplecov"
    coverage_dir = File.join(File.dirname(SimpleCov.coverage_dir), "ruby-*")
    coverage_results = Dir[File.join(coverage_dir, ".resultset.json")]

    raise <<~MSG if coverage_results.empty?
      Coverage results not found, searched in:
      #{Dir[coverage_dir].map { |dir| "  - #{dir}" }.join("\n")}
    MSG

    SimpleCov.collate(coverage_results) do
      coverage_dir "coverage"
    end
  end
end

desc "Run coverage analysis and collate coverage results"
task coverage: ["coverage:run", "coverage:report"]
