plugins:
  - rubocop-rake
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Style/HashSyntax:
  EnforcedShorthandSyntax: consistent

Style/Documentation:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/BlockDelimiters:
  EnforcedStyle: line_count_based

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true
  AllowMultilineFinalElement: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineHashBraceLayout:
  EnforcedStyle: new_line

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Metrics/ClassLength:
  Exclude:
    - lib/stimulus_plumbers/themes/**/*.rb
    - test/stimulus_plumbers/themes/**/*_test.rb
    - test/stimulus_plumbers/form/builder_test.rb

Metrics/ModuleLength:
  Exclude:
    - lib/stimulus_plumbers/components/plumber/stimulus_registry.rb

Metrics/MethodLength:
  Exclude:
    - lib/stimulus_plumbers/themes/**/*.rb
    - lib/stimulus_plumbers/components/**/*.rb
    - lib/stimulus_plumbers/form/fields/*.rb
    - test/system/**/*_test.rb

Metrics/AbcSize:
  Exclude:
    - lib/stimulus_plumbers/form/builder.rb
    - lib/stimulus_plumbers/components/**/*.rb
    - lib/stimulus_plumbers/form/fields/*.rb
    - lib/stimulus_plumbers/themes/base.rb
    - test/system/**/*_test.rb

Layout/LineLength:
  Max: 125

Metrics/ParameterLists:
  Exclude:
    - lib/stimulus_plumbers/components/**/*.rb
    - lib/stimulus_plumbers/form/field_component.rb
    - lib/stimulus_plumbers/form/fields/*.rb
    - lib/stimulus_plumbers/helpers/*.rb

Minitest/MultipleAssertions:
  Max: 5
  Exclude:
    - test/system/**/*_test.rb
