# frozen_string_literal: true

source "https://rubygems.org"

gemspec

gem "railties", ">= 6.1", "< 8.2"
gem "view_component", "~> 3.0"

group :development, :test do
  gem "rails", ">= 6.1", "< 8.2"
  gem "rake", "~> 13.3"

  gem "simplecov", "~> 0.22.0", require: false
  gem "simplecov-cobertura", require: false
end

group :development do
  gem "rubocop", "~> 1.85", require: false
  gem "rubocop-minitest", require: false
  gem "rubocop-rake", require: false

  gem "appraisal", "~> 2.5.0", require: false
end

group :test do
  gem "capybara", "~> 3.39" # last version to support Ruby 2.7
  gem "minitest", "~> 5.25"
end
