name: CI (Lint)
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint-md-docs:
    name: "markdown (docs)"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          cache: npm
          cache-dependency-path: package-lock.json

      - run: npm ci
      - run: npm run format:docs:check

  lint-eslint-npm:
    name: "eslint (npm)"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: stimulus-plumbers

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          cache: npm
          cache-dependency-path: stimulus-plumbers/package-lock.json

      - run: npm ci
      - run: npm run lint

  lint-prettier-npm:
    name: "prettier (npm)"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: stimulus-plumbers

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          cache: npm
          cache-dependency-path: stimulus-plumbers/package-lock.json

      - run: npm ci
      - run: npm run format:check

  lint-rubocop-rails:
    name: "rubocop (rails)"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: stimulus-plumbers-rails
    env:
      BUNDLE_GEMFILE: "${{ github.workspace }}/stimulus-plumbers-rails/Gemfile"

    steps:
      - uses: actions/checkout@v6
      - run: rm Gemfile.lock

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler: latest
          bundler-cache: true

      - run: bundle exec rake rubocop

  lint-rubocop-tailwind:
    name: "rubocop (tailwind)"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: stimulus-plumbers-tailwind
    env:
      BUNDLE_GEMFILE: "${{ github.workspace }}/stimulus-plumbers-tailwind/Gemfile"

    steps:
      - uses: actions/checkout@v6
      - run: rm Gemfile.lock

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler: latest
          bundler-cache: true

      - run: bundle exec rake rubocop
