name: CI (Rails)
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 12 * * 5'

defaults:
  run:
    working-directory: stimulus-plumbers-rails

permissions:
  contents: read

jobs:
  test-rails:
    name: "Rails ${{ matrix.rails-version }} / Ruby ${{ matrix.ruby-version }}"
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: "${{ github.workspace }}/stimulus-plumbers-rails/gemfiles/rails_${{ matrix.rails-version }}.gemfile"
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
          - "3.4"
          - "4.0"
          - "head"
        rails-version:
          - "6.1"
          - "7.0"
          - "7.1"
          - "7.2"
          - "8.0"
          - "8.1"
        include:
          - ruby-version: "3.3"
            rails-version: "edge"
          - ruby-version: "3.4"
            rails-version: "edge"
          - ruby-version: "4.0"
            rails-version: "edge"
          - ruby-version: "head"
            rails-version: "edge"
        exclude:
          # ruby >= 3.1 for rails >= 7.2
          - ruby-version: "2.7"
            rails-version: "7.2"
          - ruby-version: "3.0"
            rails-version: "7.2"
          # ruby >= 3.2 for rails == 8.0
          - ruby-version: "2.7"
            rails-version: "8.0"
          - ruby-version: "3.0"
            rails-version: "8.0"
          - ruby-version: "3.1"
            rails-version: "8.0"
          # ruby >= 3.2 for rails >= 8.1
          - ruby-version: "2.7"
            rails-version: "8.1"
          - ruby-version: "3.0"
            rails-version: "8.1"
          - ruby-version: "3.1"
            rails-version: "8.1"

    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v6

        # https://bundler.io/blog/2018/01/17/making-gem-development-a-little-better.html
      - run: rm Gemfile.lock
      - run: rm gemfiles/*.gemfile.lock

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          rubygems: 3.4.22 # last version to support Ruby 2.7
          bundler: latest
          bundler-cache: true

      - run: "bundle exec appraisal rails-${{ matrix.rails-version }} rake test:unit"
      - run: "bundle exec appraisal rails-${{ matrix.rails-version }} rake test:system"
