name: Release
run-name: Release stimulus-plumbers ${{ inputs.version }}
concurrency:
  group: release
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version (e.g. 1.0.0)
        required: true
        type: string

env:
  VERSION: ${{ inputs.version }}

jobs:
  npm:
    name: Publish @stimulus-plumbers/controllers to NPM
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: stimulus-plumbers
    permissions:
      contents: write
      id-token: write
    environment: release
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org
          cache: npm
          cache-dependency-path: stimulus-plumbers/package-lock.json

      - run: npm ci

      - run: npm version ${{ env.VERSION }} --no-git-tag-version

      - uses: orhun/git-cliff-action@v4
        with:
          config: stimulus-plumbers/cliff.toml
          args: --tag stimulus-plumbers/v${{ env.VERSION }}
        env:
          OUTPUT: stimulus-plumbers/CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - uses: ryancyq/github-signed-commit@v1
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          files: |
            stimulus-plumbers/package.json
            stimulus-plumbers/package-lock.json
            stimulus-plumbers/CHANGELOG.md
          commit-message: "Bump npm @stimulus-plumbers/controllers version to ${{ env.VERSION }}"
          tag: stimulus-plumbers/v${{ env.VERSION }}

      - run: npm run build

      - uses: actions/upload-artifact@v7
        with:
          name: stimulus-plumbers-dist
          path: stimulus-plumbers/dist/

      - name: Publish to NPM
        run: npm publish --provenance --access public

  rubygem-rails:
    name: Publish stimulus-plumbers to RubyGems
    runs-on: ubuntu-latest
    needs: npm
    defaults:
      run:
        working-directory: stimulus-plumbers-rails
    permissions:
      contents: write
      id-token: write
    environment: release
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v8
        with:
          name: stimulus-plumbers-dist
          path: stimulus-plumbers-rails/app/assets/javascripts/stimulus-plumbers

      # https://bundler.io/blog/2018/01/17/making-gem-development-a-little-better.html
      - run: rm Gemfile.lock
      - run: rm gemfiles/*.gemfile.lock

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler: 2.7.2
          bundler-cache: true

      - run: bin/bump-version ${{ env.VERSION }}
        shell: bash

      - run: bundle exec rake appraisal:setup
      - run: bundle exec rake rubocop:autocorrect_all

      - uses: orhun/git-cliff-action@v4
        with:
          config: stimulus-plumbers-rails/cliff.toml
          args: --tag stimulus-plumbers-rails/v${{ env.VERSION }}
        env:
          OUTPUT: stimulus-plumbers-rails/CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - uses: ryancyq/github-signed-commit@v1
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          files: |
            stimulus-plumbers-rails/Gemfile.lock
            stimulus-plumbers-rails/gemfiles/*.gemfile.lock
            stimulus-plumbers-rails/lib/stimulus_plumbers/version.rb
            stimulus-plumbers-rails/CHANGELOG.md
          commit-message: "Bump rubygem stimulus-plumbers version to ${{ env.VERSION }}"
          tag: stimulus-plumbers-rails/v${{ env.VERSION }}

      - run: bundle exec rake build

      - name: Configure RubyGems trusted publishing credentials
        uses: rubygems/configure-rubygems-credentials@v2.1.0

      - name: Push gem
        run: |
          for gem in pkg/stimulus-plumbers-$VERSION*.gem ; do
            gem push "$gem" --host https://rubygems.org
          done
        shell: bash

  rubygem-tailwind:
    name: Publish stimulus-plumbers-tailwind to RubyGems
    runs-on: ubuntu-latest
    needs: rubygem-rails
    defaults:
      run:
        working-directory: stimulus-plumbers-tailwind
    permissions:
      contents: write
      id-token: write
    environment: release
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - run: rm Gemfile.lock

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler: 2.7.2
          bundler-cache: true

      - run: bin/bump-version ${{ env.VERSION }}
        shell: bash

      - run: bundle exec rake rubocop:autocorrect_all

      - uses: orhun/git-cliff-action@v4
        with:
          config: stimulus-plumbers-tailwind/cliff.toml
          args: --tag stimulus-plumbers-tailwind/v${{ env.VERSION }}
        env:
          OUTPUT: stimulus-plumbers-tailwind/CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - uses: ryancyq/github-signed-commit@v1
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          files: |
            stimulus-plumbers-tailwind/Gemfile.lock
            stimulus-plumbers-tailwind/lib/stimulus_plumbers/tailwind/version.rb
            stimulus-plumbers-tailwind/CHANGELOG.md
          commit-message: "Bump rubygem stimulus-plumbers-tailwind version to ${{ env.VERSION }}"
          tag: stimulus-plumbers-tailwind/v${{ env.VERSION }}

      - run: bundle exec rake build

      - name: Configure RubyGems trusted publishing credentials
        uses: rubygems/configure-rubygems-credentials@v2.1.0

      - name: Push gem
        run: |
          for gem in pkg/stimulus-plumbers-tailwind-$VERSION*.gem ; do
            gem push "$gem" --host https://rubygems.org
          done
        shell: bash
