# frozen_string_literal: true

require "json"
require "action_view/version"
require "uri" if ActionView.version < Gem::Version.new("7.3")
require "mcp"
require "action_view"
require "stimulus_plumbers"
require "stimulus_plumbers_tailwind"

require_relative "stimulus_plumbers_mcp/version"
require_relative "stimulus_plumbers/mcp/loaders/guide_loader"
require_relative "stimulus_plumbers/mcp/loaders/schema_loader"
require_relative "stimulus_plumbers/mcp/loaders/docs_loader"
require_relative "stimulus_plumbers/mcp/loaders/stimulus_manifest"
require_relative "stimulus_plumbers/mcp/loaders/component_controller_map"
require_relative "stimulus_plumbers/mcp/loaders/theme_loader"
require_relative "stimulus_plumbers/mcp/loaders/tailwind_theme_loader"
require_relative "stimulus_plumbers/mcp/plugins/base"
require_relative "stimulus_plumbers/mcp/plugins/guide"
require_relative "stimulus_plumbers/mcp/plugins/schema"
require_relative "stimulus_plumbers/mcp/plugins/docs"
require_relative "stimulus_plumbers/mcp/plugins/stimulus"
require_relative "stimulus_plumbers/mcp/plugins/theme"
require_relative "stimulus_plumbers/mcp/plugins/tailwind"
require_relative "stimulus_plumbers/mcp/server"
